---
- name: Deploy Nomad + Consul
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Set additional facts
      ansible.builtin.include_role:
        name: set_facts
  tasks:
    - name: Include Nomad + Consul playbook
      ansible.builtin.import_playbook: anultravioletaurora.nomadintosh.nomadintosh
