---
- name: Deploy Nomadintosh
  ansible.builtin.import_playbook: anultravioletaurora.nomadintosh.nomadintosh

- name: Deploy Nomaduntu
  ansible.builtin.import_playbook: anultravioletaurora.nomaduntu.nomaduntu
